name: build-and-deploy
on:
  workflow_dispatch: {}
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Use 3.9 for widest sklearn compatibility
      - uses: actions/setup-python@v5
        with: { python-version: "3.9" }

      - name: Install deps (pinned for CI)
        run: |
          python -m pip install --upgrade pip
          pip install "numpy==1.26.4" "pandas==1.5.3" "scikit-learn==1.3.2" boto3 yfinance
          # If you have extra libs in requirements.txt, install them without re-pinning core deps:
          if [ -f requirements.txt ]; then pip install --no-deps -r requirements.txt; fi

      - name: Build dashboard (writes ./public/index.html)
        env:
          PRICES_FEATURES_PATH: data/processed/prices_features_public.csv
          ARIMA_PUBLIC_PATH:    data/processed/arima_results_public.csv
          
          TICKERS: AAPL,MSFT,INTC,BTC-USD
        run: |
          python -m dashboard.dashboard
          test -f public/index.html

      - name: Upload artifact for Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public


  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
