name: Deploy dashboard to Pages
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: ${{ runner.os }}-pip-

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      # ---- 1) Build data artifacts ----
      - name: Make features
        run: python etl/feature_engineering.py

      - name: Run ARIMA
        run: python modeling/time_series_arima.py

      # ---- 2) Sanity check data exists ----
      - name: Sanity check data/processed
        run: |
          ls -la data/processed || true
          python - << 'PY'
          import os, pandas as pd
          paths = [
            "data/processed/prices_features_public.csv",
            "data/processed/arima_results_public.csv",
          ]
          for p in paths:
            print("EXISTS", p, os.path.exists(p))
            if os.path.exists(p):
              df = pd.read_csv(p)
              print(p, "rows=", len(df))
              print(df.head().to_string(index=False))
          PY

      # ---- 3) Build static site (no live hits in CI) ----
      - name: Build dashboard
        env:
          PRICES_FEATURES_PATH: data/processed/prices_features_public.csv
          ARIMA_PUBLIC_PATH:    data/processed/arima_results_public.csv
          FETCH_LIVE: "0"
          REQUIRE_ARIMA: "1"  # fail build if ARIMA missing
        run: |
          python -m dashboard.dashboard
          echo "==== HEAD predictions.csv ===="
          head -n 5 public/predictions.csv || true
          echo "==== Grep ARIMA numbers in HTML ===="
          grep -nE 'ARIMA Pred|Î”%|[0-9]+\.[0-9]{3}</td>' public/index.html || true

      # ---- 4) Upload to Pages ----
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

      # Also upload as build artifact for debugging (optional)
      - name: Upload build artifact (debug)
        uses: actions/upload-artifact@v4
        with:
          name: site-build
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
